In [10]:
2+2

4

In [11]:
import pandas as pd
from glob import glob
from parse import parse
from tqdm import tqdm

t = [1,3,5,7,9,11.0,13.0,15.0,17.0,19.0,21.0,23.0,25.0,27.0,29.0,31.0,33.0,35.0,37.0,39.0,42.5,47.5,52.5,57.5,62.5,67.5,72.5,77.5,82.5,87.5,95.0,105,115,125,135,145,155,165,175,185,195,205,215,225,235,270,330,390,450,510,570,660,780,900,1020,1140,1260,1380,1500,1620,1740,1950,2250,2550,2850,3150,3450,3750,4050]

dfs = []
for p in tqdm(glob("/depict/users/hinge/private/hedypet/dynamic/*/totalseg_erosion*/tac*")):
    o = parse("/depict/users/hinge/private/hedypet/dynamic/{sub}/{task}_erosion-{erosion:d}/tac_{}_{seg:d}",p)
    df = pd.read_csv(p)
    for k,v in o.named.items():
        df[k] = v
    df["t"] = t
    df["tix"] = list(range(len(t)))
    dfs.append(df)

100%|██████████| 43353/43353 [01:26<00:00, 498.37it/s]

In [14]:
md = pd.read_csv("/depict/data/hedit/raw/participants.tsv",sep="\t")
md["age-group"] = md["demographic-group"].apply(lambda x: x[1:])
md["gender"] = md["demographic-group"].apply(lambda x: x[0])
dft = pd.concat(dfs)
dft["age-group"] = dft["sub"].map(md.set_index("participant_id")["age-group"])
dft["gender"] = dft["sub"].map(md.set_index("participant_id")["gender"])

In [13]:
dft

,mu,std,n,sub,task,erosion,seg,t,tix,age-group,gender
0,0.000000,0.000000,61988,sub-000,totalseg,0,1,1.0,0,18-34,M
1,0.000000,0.000000,61988,sub-000,totalseg,0,1,3.0,1,18-34,M
2,0.000000,0.000000,61988,sub-000,totalseg,0,1,5.0,2,18-34,M
3,0.000000,0.000000,61988,sub-000,totalseg,0,1,7.0,3,18-34,M
4,0.000000,0.000000,61988,sub-000,totalseg,0,1,9.0,4,18-34,M
...,...,...,...,...,...,...,...,...,...,...,...
64,196.080780,79.216545,17298,sub-099,totalseg,2,117,2850.0,64,70-99,M
65,179.077637,77.885231,17298,sub-099,totalseg,2,117,3150.0,65,70-99,M
66,168.324661,73.533134,17298,sub-099,totalseg,2,117,3450.0,66,70-99,M
67,162.278091,70.183105,17298,sub-099,totalseg,2,117,3750.0,67,70-99,M
68,183.302887,77.835587,17298,sub-099,totalseg,2,117,4050.0,68,70-99,M

In [16]:
pd.read_pickle("v1.pkl.gz")

,mu,std,n,sub,task,erosion,seg,t,tix,age-group,gender
0,0.000000,0.000000,61988,sub-000,totalseg,0,1,1.0,0,18-34,M
1,0.000000,0.000000,61988,sub-000,totalseg,0,1,3.0,1,18-34,M
2,0.000000,0.000000,61988,sub-000,totalseg,0,1,5.0,2,18-34,M
3,0.000000,0.000000,61988,sub-000,totalseg,0,1,7.0,3,18-34,M
4,0.000000,0.000000,61988,sub-000,totalseg,0,1,9.0,4,18-34,M
...,...,...,...,...,...,...,...,...,...,...,...
64,196.080780,79.216545,17298,sub-099,totalseg,2,117,2850.0,64,70-99,M
65,179.077637,77.885231,17298,sub-099,totalseg,2,117,3150.0,65,70-99,M
66,168.324661,73.533134,17298,sub-099,totalseg,2,117,3450.0,66,70-99,M
67,162.278091,70.183105,17298,sub-099,totalseg,2,117,3750.0,67,70-99,M
68,183.302887,77.835587,17298,sub-099,totalseg,2,117,4050.0,68,70-99,M

In [15]:
dft.to_pickle("v1.pkl.gz")

In [7]:
import json
data = []
for p in tqdm(glob("/depict/users/hinge/private/hedypet/dynamic/*/norm.json")):
    with open(p,"r") as handle:
        d = json.load(handle)
    sub = parse("/depict/users/hinge/private/hedypet/dynamic/{}/norm.json",p)[0]
    d["sub"] = sub
    data.append(d)
df = pd.DataFrame(data)
df.to_pickle("norm.pkl")

100%|██████████| 100/100 [00:00<00:00, 18737.12it/s]